data:extend(
{
	{
    type = "bool-setting",
    name = "lasertanks-override-color",
    setting_type = "startup",
    default_value = false,
	order = "f",
    per_user = false,
	},
    {
    type = "double-setting",
    name = "lasertanks-color-r",
    setting_type = "startup",
    default_value = 1.0,
    maximum_value = 1.0,
    minimum_value = 0,
	order = "g1",
    per_user = false,
	},
	{
    type = "double-setting",
    name = "lasertanks-color-g",
    setting_type = "startup",
    default_value = 1.0,
    maximum_value = 1.0,
    minimum_value = 0,
	order = "g2",
    per_user = false,
	},
	{
    type = "double-setting",
    name = "lasertanks-color-b",
    setting_type = "startup",
    default_value = 1.0,
    maximum_value = 1.0,
    minimum_value = 0,
	order = "g3",
    per_user = false,
	},
    {
    type = "int-setting",
    name = "lasertanks-explosions",
    setting_type = "startup",
    default_value = 10,
    maximum_value = 10,
    minimum_value = 1,
	order = "h",
    per_user = false,
	},
	{
    type = "bool-setting",
    name = "lasertanks-aai-tank",
    setting_type = "startup",
    default_value = true,
	order = "i",
    per_user = false,
	},
	{
    type = "bool-setting",
    name = "lasertanks-electric-engine",
    setting_type = "startup",
    default_value = true,
	order = "j",
    per_user = false,
	},
	{
    type = "bool-setting",
    name = "lasertanks-add-train",
    setting_type = "startup",
    default_value = true,
	order = "k",
    per_user = false,
	},
})