data:extend
{
  {
    type = "item",
    name = "electric-vehicles-lo-voltage-transformer",
    icon = "__Laser_Tanks_kr__/graphics/icons/lo-voltage-transformer.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-lo-voltage-transformer",
    flags = {},
    subgroup = "electric-vehicles-equipment",
    order = "c",
    stack_size = 10,
  },
  {
    type = "item",
    name = "electric-vehicles-hi-voltage-transformer",
    icon = "__Laser_Tanks_kr__/graphics/icons/hi-voltage-transformer.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-hi-voltage-transformer",
    flags = {},
    subgroup = "electric-vehicles-equipment",
    order = "d",
    stack_size = 10,
  },
  {
    type = "item",
    name = "electric-vehicles-regen-brake-controller",
    icon = "__Laser_Tanks_kr__/graphics/icons/regen-brake-controller.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-regen-brake-controller",
    flags = {},
    subgroup = "electric-vehicles-equipment",
    order = "e",
    stack_size = 10,
  },
}
